version: "3"
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    working_dir: /store
    volumes:
      - './:/store'
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres:postgres
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
volumes:
  postgres_data:
    driver: local
